package idem

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"

	"github.com/youndie/tacku/server/internal/domain"
)

// Header is the one SPEC.md §16.5 names.
const Header = "Idempotency-Key"

// Middleware makes a repeat produce nothing at all.
//
// It sits above the handler rather than inside it, and that placement is the whole point. The
// specification warns about exactly this: an engine can correctly decline to repeat an operation
// while the route handler goes on to duplicate its side effects — a line in the journal, a frame on
// an update channel, a message sent. Wrapping the domain call protects the operation; wrapping the
// handler protects everything the handler does.
//
// It also makes the guarantee structural. A submit added next month is covered by having been
// mounted, rather than by whoever wrote it remembering.
func Middleware(attempts domain.Attempts, next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Only what changes state. §16.5 is about submits, and demanding a key to read a screen
		// would be a rule with no failure behind it.
		if r.Method != http.MethodPost {
			next.ServeHTTP(w, r)
			return
		}

		key := r.Header.Get(Header)
		if key == "" {
			// 400 rather than 422: the request is malformed rather than refused on its merits, and
			// the difference tells a client to fix the call rather than the data.
			writeError(w, http.StatusBadRequest, Header+" is required")
			return
		}

		body, err := io.ReadAll(io.LimitReader(r.Body, maxBody))
		if err != nil {
			writeError(w, http.StatusBadRequest, "the body could not be read")
			return
		}
		_ = r.Body.Close()
		r.Body = io.NopCloser(bytes.NewReader(body))

		hash, err := hashRequest(json.RawMessage(body))
		if err != nil {
			writeError(w, http.StatusBadRequest, "the body is not JSON")
			return
		}

		scoped := scope(r.URL.Path, key)
		previous, found, err := attempts.Outcome(r.Context(), scoped)
		if err != nil {
			writeError(w, http.StatusInternalServerError, "the attempt could not be looked up")
			return
		}
		if found {
			if previous.RequestHash != hash {
				writeError(w, http.StatusConflict, "this idempotency key was used for a different request")
				return
			}
			// Replayed without calling the handler at all, which is what makes the side effects
			// safe rather than merely the operation.
			var stored response
			if err := json.Unmarshal(previous.Body, &stored); err != nil {
				writeError(w, http.StatusInternalServerError, "the recorded outcome is unreadable")
				return
			}
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(stored.Status)
			_, _ = w.Write(stored.Body)
			return
		}

		recorder := &recording{ResponseWriter: w, status: http.StatusOK}
		next.ServeHTTP(recorder, r)

		// Only a success is remembered. A refusal recorded would mean a request corrected after one
		// could never succeed under the key it was refused with.
		if recorder.status < 200 || recorder.status > 299 {
			return
		}

		outcome, err := json.Marshal(response{Status: recorder.status, Body: recorder.body.Bytes()})
		if err != nil {
			return
		}
		_ = attempts.Remember(r.Context(), scoped, domain.Outcome{RequestHash: hash, Body: outcome})
	})
}

// maxBody bounds what is read before anything is decided. A submit is a form, not an upload.
const maxBody = 1 << 20

// scope keeps the key spaces of the two surfaces apart.
//
// A key is generated by a client, and the same string arriving at a tool call and at a submit would
// otherwise replay one shape of answer into the other. The path is enough: an MCP tool records under
// its own name.
func scope(path, key string) string { return "http:" + path + ":" + key }

type response struct {
	Status int             `json:"status"`
	Body   json.RawMessage `json:"body"`
}

// recording keeps what the handler wrote so that it can be replayed.
type recording struct {
	http.ResponseWriter
	status int
	body   bytes.Buffer
}

func (r *recording) WriteHeader(status int) {
	r.status = status
	r.ResponseWriter.WriteHeader(status)
}

func (r *recording) Write(p []byte) (int, error) {
	r.body.Write(p)
	return r.ResponseWriter.Write(p)
}

func writeError(w http.ResponseWriter, status int, message string) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(map[string]string{"error": message})
}
